#!/usr/bin/env bash
# ops-6 (ADR-0007 D8) — dashboard prepare step: glue, not kernel.
#
# Rebuilds the graph, writes the four data JSONs the views read, then embeds
# them into _generated-data.qmd as base64 OJS cells. The data is embedded at
# render time and never fetched, so the rendered site works over file:// (D1):
# browsers block fetch()/module loads over file://, so there is no FileAttachment
# of separate data files. Base64 keeps doc titles (backticks, quotes, em-dashes)
# out of the JS string literal; the payload is ASCII-escaped JSON so the
# browser-side `JSON.parse(atob(...))` roundtrips losslessly.
#
# Everything written here is derived and gitignored. The committed part is the
# view definitions (_quarto.yml, index.qmd) and this script.
set -euo pipefail

ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
cd "$ROOT"

DATA="dashboards/data"
mkdir -p "$DATA"

cli() { bun bin/cli.ts "$@"; }

# 1. Rebuild the graph from the live tree so every view reads the same "now".
#    coverage reads the store; export and diff parse the tree fresh.
cli graph build >/dev/null

# 2. State rollup + coverage matrix — straight from the CLI JSON contracts.
#    coverage already folds evals/coverage-exceptions.md into unmeasured[].reason.
cli graph export          > "$DATA/state.json"
cli graph coverage --json > "$DATA/coverage.json"

# 3. Since-last-visit: diff from the previous STATE.md-touching commit to HEAD.
#    STATE.md regenerates when work concludes, so its git history is the session
#    heartbeat. No earlier commit ⇒ no last visit ⇒ an empty object, which the
#    view renders as the honest "nothing since the last heartbeat" state.
ANCHOR="$(git log --skip 1 -1 --format=%H -- docs/STATE.md || true)"
if [ -n "$ANCHOR" ]; then
  cli graph diff "$ANCHOR" HEAD --json > "$DATA/diff.json"
else
  echo '{}' > "$DATA/diff.json"
fi

# 4. _generated-data.qmd (embedded data). Per-record bench detail and the
#    per-metric trend substrate ride INSIDE state.json (`bench.runs`,
#    `bench.metric_values`) — computed by the kernel's parseRunRecords and
#    computeMetrics, so this script re-derives no verdict rule (bench-2
#    dissolved the duplication). runs.json is kept as an extracted convenience
#    view of the same kernel rows.
bun run - <<'FINALIZE'
import * as fs from 'node:fs';
import * as path from 'node:path';

const DATA = 'dashboards/data';

const state = JSON.parse(
  fs.readFileSync(path.join(DATA, 'state.json'), 'utf-8'),
);
fs.writeFileSync(
  path.join(DATA, 'runs.json'),
  JSON.stringify(state.bench.runs, null, 2),
);

// Escape every char above 0x7e to \uXXXX so the base64 payload is pure ASCII.
// atob() returns bytes-as-chars; on multi-byte UTF-8 (em-dashes in titles) that
// would mojibake. Escaped, atob() roundtrips exactly and JSON.parse turns the
// \uXXXX back into the character. Written as a char-code loop so this source
// file carries no non-ASCII literals of its own.
function asciiEscape(json) {
  let out = '';
  for (let i = 0; i < json.length; i++) {
    const code = json.charCodeAt(i);
    out +=
      code > 0x7e ? '\\u' + code.toString(16).padStart(4, '0') : json[i];
  }
  return out;
}

function embed(name, file) {
  const raw = fs.readFileSync(path.join(DATA, file), 'utf-8');
  const compact = JSON.stringify(JSON.parse(raw)); // validate + shrink
  const b64 = Buffer.from(asciiEscape(compact), 'ascii').toString('base64');
  // output: false — in `format: dashboard`, cells without it get no DOM slot when
  // they sit outside a page's card layout, and Quarto's OJS connector then crashes
  // on cellDiv.classList, taking dependent cells' rendering down with it.
  return '```{ojs}\n//| echo: false\n//| output: false\n' + name + ' = JSON.parse(atob("' + b64 + '"))\n```';
}

const cells = [
  embed('state', 'state.json'),
  embed('coverage', 'coverage.json'),
  embed('diff', 'diff.json'),
];
const header =
  '<!-- Generated by dashboards/prepare.sh. Do not edit by hand: regenerate. -->\n';
fs.writeFileSync(
  'dashboards/_generated-data.qmd',
  header + cells.join('\n\n') + '\n',
);
console.log(
  `embedded ${state.bench.runs.length} kernel run record(s) -> dashboards/_generated-data.qmd`,
);
FINALIZE

echo "prepare: wrote $DATA/{state,coverage,diff,runs}.json + dashboards/_generated-data.qmd"
